#!/usr/bin/env python3
"""Regenerate README.md from gkneighb's public GitHub activity.

Pulls from the Search API (no event-API 90-day cutoff). Stdlib only — runs on
any plain ubuntu-latest runner without dependency installation.

Set GITHUB_TOKEN in the env to avoid the unauthenticated rate limit.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.parse
import urllib.request
from collections import defaultdict
from datetime import datetime, timezone

USERNAME = "gkneighb"
TOKEN = os.environ.get("GITHUB_TOKEN")


def gh(path: str) -> dict:
    url = f"https://api.github.com{path}"
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def search_all(query: str) -> list[dict]:
    encoded = urllib.parse.quote_plus(query)
    items: list[dict] = []
    for page in range(1, 11):
        data = gh(f"/search/issues?q={encoded}&per_page=100&page={page}&sort=created&order=desc")
        page_items = data.get("items", [])
        items.extend(page_items)
        if len(page_items) < 100:
            break
    return items


def repo_of(item: dict) -> str:
    return item["repository_url"].removeprefix("https://api.github.com/repos/")


def date(s: str | None) -> str:
    return s[:10] if s else ""


def render_pr_table(prs: list[dict]) -> str:
    if not prs:
        return "_None yet._\n"
    lines = ["| Repo | PR | Title | Opened | Status |", "|---|---|---|---|---|"]
    for pr in prs:
        repo = repo_of(pr)
        pull = pr.get("pull_request") or {}
        if pull.get("merged_at"):
            status = f"merged {date(pull['merged_at'])}"
        elif pr["state"] == "closed":
            status = f"closed {date(pr['closed_at'])}"
        else:
            status = "open"
        title = pr["title"].replace("|", "\\|")
        lines.append(
            f"| `{repo}` | [#{pr['number']}]({pr['html_url']}) | {title} | {date(pr['created_at'])} | {status} |"
        )
    return "\n".join(lines) + "\n"


def render_issue_table(items: list[dict]) -> str:
    if not items:
        return "_None yet._\n"
    lines = ["| Repo | Issue | Title | State |", "|---|---|---|---|"]
    for it in items:
        repo = repo_of(it)
        state = it["state"]
        if state == "closed" and it.get("closed_at"):
            state = f"closed {date(it['closed_at'])}"
        title = it["title"].replace("|", "\\|")
        lines.append(
            f"| `{repo}` | [#{it['number']}]({it['html_url']}) | {title} | {state} |"
        )
    return "\n".join(lines) + "\n"


def is_upstream(item: dict) -> bool:
    """Filter out activity in repos owned by USERNAME (own forks/personal repos)."""
    return not repo_of(item).startswith(f"{USERNAME}/")


def main() -> int:
    prs = [p for p in search_all(f"author:{USERNAME} is:pr") if is_upstream(p)]
    issues_opened = [i for i in search_all(f"author:{USERNAME} is:issue") if is_upstream(i)]
    # Issues I commented on but did not open. Filter to closed ones — these are
    # the higher-signal entries (verification/triage that moved a bug forward).
    commented = [
        i for i in search_all(f"commenter:{USERNAME} is:issue -author:{USERNAME}")
        if is_upstream(i)
    ]
    commented_closed = [i for i in commented if i["state"] == "closed"]
    commented_open = [i for i in commented if i["state"] != "closed"]

    merged = [p for p in prs if (p.get("pull_request") or {}).get("merged_at")]
    open_prs = [p for p in prs if p["state"] == "open"]
    other_prs = [p for p in prs if p["state"] == "closed" and not (p.get("pull_request") or {}).get("merged_at")]

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    body = f"""# Open Source Contributions

Public activity for [`@{USERNAME}`](https://github.com/{USERNAME}). Auto-generated by [`generate.py`](generate.py); refreshed nightly via GitHub Actions. Last update: **{now}**.

| Metric | Count |
|---|---|
| Pull requests opened | {len(prs)} |
| &nbsp;&nbsp;&nbsp;&nbsp;merged | {len(merged)} |
| &nbsp;&nbsp;&nbsp;&nbsp;open | {len(open_prs)} |
| Issues opened | {len(issues_opened)} |
| Issues commented on (closed) | {len(commented_closed)} |
| Issues commented on (open) | {len(commented_open)} |

## Merged pull requests

{render_pr_table(merged)}
## Open pull requests

{render_pr_table(open_prs)}
"""

    if other_prs:
        body += f"## Other pull requests\n\n{render_pr_table(other_prs)}\n"

    body += f"""## Issues opened

{render_issue_table(issues_opened)}
## Issues commented on (closed)

Bugs I commented on that subsequently closed. Often these were stale reports where my comment confirmed reproduction status on a current version.

{render_issue_table(commented_closed)}
## Issues commented on (open)

{render_issue_table(commented_open)}
"""

    path = os.path.join(os.path.dirname(__file__), "README.md")
    with open(path, "w") as f:
        f.write(body)
    print(f"wrote {path} ({len(body)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
